### ISSUE TITLE
资源下载下来打不开

### ISSUE THREAD

**Issue by zengqingfa** [dlod-openvino/book#6]
资源下载下来打不开，报文件已损坏什么的，两个网盘的都是

**Comment by dlod-openvino** [comment]
https://yunpan.360.cn/surl_yqMKweHiZRL （提取码：af62）

麻烦试试上面的链接



***@***.***
 
发件人： zengqingfa
发送时间： 2021-06-18 16:40
收件人： dlod-openvino/book
抄送： Subscribed
主题： [dlod-openvino/book] 资源下载下来打不开 (#6)
资源下载下来打不开，报文件已损坏什么的，两个网盘的都是
